---
- hosts: webservers
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=installed

  - name: Start Apache service
    service: name=httpd enabled=yes state=started

- hosts: dbservers
  sudo: yes


  tasks:
  - name: Ensure mysql is installed
    yum: name=mysql-server state=present
  - name: mysql start
    service: name=mysqld state=started

- hosts: webservers:dbservers
  sudo: yes

  tasks:
  - name: stop IPTABLES!!!
    service: name=iptables state=stopped



